### ISSUE TITLE
File contains MALWARE!!! Please fix download!

### ISSUE THREAD

**Issue by WeeGreenNinja5** [mapcrafter/mapcrafter#157] opened 2015-07-26 21:43 UTC
Hello! I tried to download recently a version of mapcrafter for Windows 64-bit, and I encountered a problem when trying to download it. Chrome read the file as malicious (which in this case, might contain Malware!) The program hasn't been updated since January 2015 and I really want to render my maps to make a Park Map for 2 of my projects on PMC.com, but I also don't want to get malware on my brand new PC. Can you at least update the program for Windows by making it a safe download at least? I would really appreciate it! Here's a screenshot when I tried downloading it:

![unsafe download](https://cloud.githubusercontent.com/assets/13194741/8896058/a1d70b76-33a4-11e5-9d37-81b5d6fc6a35.png)

Thanks for reading and I hope you can fix it!

**Comment by thorerik** [comment] 2015-07-26 22:48
There haven't been much changes since the latest pre-compiled available on the site.

Looking at the details for the reason it's been labled as mallicious might be heuristics taging it as mallicious:
https://www.virustotal.com/en/file/54b00448a5f79cc4eb754ebe8ef425570246ab3bfdff7b6e0d0fad5ba20bb2d8/analysis/

I've removed the offending file from this download: http://thor.re/mapcrafter_1.5.4_win64_notestconfig.zip
Here's the VT scan of the file: https://www.virustotal.com/en/file/8e429974dc064c74b8e0daca04924f09a680bb5763610ff71c747ab66e651e3c/analysis/1437950844/

It should be mostly functional even without that, my best guess to why it triggers is that it's a PE file, but this is something Moritz have to look into when he got time.

Thanks for the report :+1:

**Comment by thorerik** [comment] 2015-07-26 23:16
m0r13: removed old packages and rebuild them without testconfig.exe: http://mapcrafter.org/downloads


We'll try figure out why testconfig.exe was labled as malware (it really isn't)

**Comment by WeeGreenNinja5** [comment] 2015-07-27 07:11
Thanks for reviewing the issue! I await the download link to be safe soon! (I still get the same screen, when I download the new file, but now I'm relieved that you've taken notice of this!)

**Comment by m0r13** [comment] 2015-07-27 12:20
Actually I rebuilt only the latest 32- and 64-bit package (but I guess I will have to do that for the older packages too) they should be safe according to virustotal and google. Google just blocks all .zips on that site as I see, I hope they will unblock them when I completely remove and rebuild the old packages, but first I would also like to find out why testtextures.exe is labeled as malware.

@thorerik a PE-File? Isn't that the general name for the Win*** executable file format?

**Comment by m0r13** [comment] 2015-09-09 02:02
Let's close this as the problem is fixed and the files on mapcrafter.org are not blocked anymore by Google or other online anti virus websites.

**Closed by m0r13** 2015-09-09 02:02 UTC
