### ISSUE TITLE
Segmentation fault in lighting.cpp

### ISSUE THREAD

**Issue by tmyt** [mapcrafter/mapcrafter#187] opened 2015-11-16 06:24 UTC
I got Segmentation fault in mapcrafter::renderer::LightingRenderMode::doSmoothLight(L:404) with below environment.
```cpp
403         if (light_top)
404                 renderer->lightTop(image, getCornerColors(pos, CORNERS_TOP, under_water[2] ? water_intensity : intensity));
405 }
```
> gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
> Copyright (C) 2010 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

When issue occurred ``renderer`` is nullptr. 
``renderer`` is set in BaseRenderMode&lt;LightingRenderer&gt;::initialize, but LightingRenderer::TYPE was RenderModeRendererType::DUMMY.
the code expected LightingRenderer::TYPE initialized after initialize RenderModeRendererType::LIGHTING. but actually LightingRenderer::TYPE initialized **before** RenderModeRendererType::LIGHTING.

because, fail to initialize ``render`` got Segmenation fault.

### workaround
I avoid this issue with initialize LightingRenderer::TYPE explicitly.
```cpp
199 
200 const RenderModeRendererType LightingRenderer::TYPE(1);
201 
```

**Comment by m0r13** [comment] 2015-11-16 21:55
Oh, I already had that problem with some Debian packages with an older compiler as well.

I was able to fix that one by detecting problematic compiler versions with CMake, and then, if necessary, applying some sort of patch to the source. Can you delete `CMakeCache.txt` and `CMakeFiles/`, run cmake again and show me the output?

**Comment by tmyt** [comment] 2015-11-16 22:42
Yes, it is cmake output.
```
[tsumori@host mapcrafter]$ cmake -DBoost_NO_BOOST_CMAKE=ON .
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Failed
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Boost version: 1.41.0
-- Found the following Boost libraries:
--   iostreams
--   system
--   filesystem
--   program_options
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.41.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.3")
-- Found PNG: /usr/lib64/libpng.so (found version "1.2.49")
-- Found JPEG: /usr/lib64/libjpeg.so
-- Performing Test HAVE_NULLPTR
-- Performing Test HAVE_NULLPTR - Failed
-- Performing Test HAVE_ENUM_CLASS_COMPARISON
-- Performing Test HAVE_ENUM_CLASS_COMPARISON - Failed
-- Performing Test HAVE_ENUM_CLASS_FORWARD_DECLARATION
-- Performing Test HAVE_ENUM_CLASS_FORWARD_DECLARATION - Failed
-- Looking for include file endian.h
-- Looking for include file endian.h - found
-- Looking for include file sys/endian.h
-- Looking for include file sys/endian.h - not found
-- Looking for include file sys/ioctl.h
-- Looking for include file sys/ioctl.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file syslog.h
-- Looking for include file syslog.h - found
-- Performing Test HAVE_ENDIAN_CONVERSION
-- Performing Test HAVE_ENDIAN_CONVERSION - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tsumori/mapcrafter
```

**Comment by m0r13** [comment] 2015-11-30 14:58
Okay, I see. The problem is that the ``RenderModeRendererType`` that code is referring to at the initialization of the ``TYPE``-variable is an extern variable with your gcc version (it's a bad workaround unfortunately). Apparently that compiler version has a problem with the initialization of those extern variables, so ``RenderModeRendererType::LIGHTING`` is not initialized in this case. The same problem seems to exist with the sky position directions in some of the lighting code (look at the top of ``lighting.cpp``).

I am not sure what is causing this. Can you live with the workaround for now?

**Comment by tmyt** [comment] 2015-11-30 16:02
Yes, I seem works perfectly with this workaround.

**Comment by m0r13** [comment] 2015-11-30 16:26
There is are no problems with the other render modes?

On November 30, 2015 5:02:32 PM GMT+01:00, tmyt <notifications@github.com> wrote:
>Yes, I seem works perfectly with this workaround.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mapcrafter/mapcrafter/issues/187#issuecomment-160671533

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tmyt** [comment] 2015-11-30 16:54
I'm using day, night, cave renderer with isometric view. These rendering result is fine.

**Comment by m0r13** [comment] 2015-12-01 22:42
Alright. The reason you are affected by this bug is a terrible terrible workaround by the way which should be fixed with the current workaround with the render modes and overlays still going on.

**Closed** 2016-08-28 16:38 UTC
Labels: Bug
