### ISSUE TITLE
Nightly packages missing from the repo

### ISSUE THREAD

**Issue by faelnor** [mapcrafter/mapcrafter#331] opened 2019-05-14 19:40 UTC
I get a 403 on the nightly repo for Debian Stretch, and a 404 for Ubuntu Xenial.

The latest official debian release (2.4-1) can't read my world ("Unknown tag type with id 12. NBT data stream may be corrupted."), which seems to be normal as it probably isn't built from the 1.13 branch, but I then have no way of installing the latest Mapcrafter besides compiling from source.

Also, why do the nightlies use version 2.3.1 when the main release uses 2.4? This is confusing.

**Comment by elamperti** [comment] 2020-03-16 05:00
Hi @faelnor, thanks for reporting this issue!

It's a duplicate of #312, so let's follow that one. Thanks! :)

**Closed as completed by elamperti** 2020-03-16 05:00 UTC
