### ISSUE TITLE
Missing water in waterfall

### ISSUE THREAD

**Issue by tripkin** [mapcrafter/mapcrafter#178] opened 2015-09-25 16:55 UTC
I am missing the water in a waterfall 'elevator' I built descending from the two pools on the platform to it's base where there are two holes to catch the water and prevent it from spreading out. This was using MapCrafter 2.1 and a basic script. 

output_dir = /var/www/sites/mapcrafter

[world:Empire]
input_dir = /nfs/minecraft/Empire/Empire

[map:Empire]
name = Empire 25566
world = Empire
texture_dir = /home/jmitchell/.minecraft/versions/1.8.8/textures
png_indexed = true

Mapcrafter Map
![2015-09-25_10-33-18_mapcrafter](https://cloud.githubusercontent.com/assets/14840341/10106600/dec59586-6372-11e5-878f-6a89a987a594.png)

Overviewer Map
![2015-09-25_10-31-47_overviewer](https://cloud.githubusercontent.com/assets/14840341/10106616/f71ce2ec-6372-11e5-90b0-da850af01b57.png)

Both waterfalls to the right have empty space behind them and are ok, it is just the water originating on the platform that is not visible. I tried it without the png_indexed line first, no change. I also used the original textures first then added the texture_dir line to point to the 1.8.8 textures I extracted using mapcrafter_textures.py..

Any ideas?

**Comment by m0r13** [comment] 2015-09-25 17:32
Hmm that looks weird. Sometimes had issues with blocks because of strange block data, but never had a problem with water as far as I know. Maybe it's that what is causing this, but maybe it's also something else.

Can you maybe send me the region file by email so I can debug this problem. Or can you give me another case where I can reproduce the problem?

**Comment by theSignSaysDie** [comment] 2015-09-25 17:33
No idea what to do here. sweet elevator though.

**Comment by tripkin** [comment] 2015-09-25 17:36
I can send you the region file if I know what it is.

**Comment by m0r13** [comment] 2015-09-25 17:40
I guess you can see it in-game when you press F3? Otherwise take the x/z coordinates, divide them by 1024 and round down. That should be the region coordinates.

**Comment by tripkin** [comment] 2015-09-25 19:25
Hi Moritz,

I found the region section. I have included a link to it for you (too 
big for email).
http://coalsack.org/mapcrafter/region.7z

**Comment by tripkin** [comment] 2015-09-25 20:56
In case you missed it, I sent you an email from Joel Mitchell... No need to reply to this message if you got the email. Thanks again for looking at this.

**Comment by m0r13** [comment] 2015-09-25 21:57
I got the mail, no problem you are welcome. :)

**Comment by m0r13** [comment] 2015-09-27 18:44
I was able to fix it!

![screen](https://cloud.githubusercontent.com/assets/1788152/10124575/23b1066c-6526-11e5-8d87-01fe6775e09e.png)

**Comment by m0r13** [comment] 2015-09-27 19:22
It's in the master branch at the moment. I will release it with some other small things as a new version soon. In the meanwhile you can use the nightly packages or build Mapcrafter from source

**Comment by tripkin** [comment] 2015-09-27 23:41
Sweet, thanks!

**Comment by m0r13** [comment] 2015-09-28 21:56
Can you confirm that it works? I can close the issue then.

**Comment by tripkin** [comment] 2015-09-28 22:05
No problem! Since I am running Ubuntu 14.04, I installed Mapcrafter using apt-get. Can I install the source over the top of that using the installer instructions?

**Comment by m0r13** [comment] 2015-09-28 22:06
You can just build it from source and not install it at all. When you built it just run it directory from that build directory (``src/mapcrafter -c ....`` when you are in the build directory).

**Comment by tripkin** [comment] 2015-09-28 22:43
Worked just like you said, and the pictures look the same. Thanks again, we can call this closed!

**Closed** 2015-09-28 22:45 UTC
Labels: Bug
