### ISSUE TITLE
Make Marker Group Identification More Flexible by Using Regex or Line Number Matching 

### ISSUE THREAD

**Issue by agattis** [mapcrafter/mapcrafter#223] opened 2016-06-23 14:29 UTC
It's hard to move a large world from overviewer to mapcrafter when you have many hundreds of signs that don't have a Prefix. 

In this sample use case, many of the signs use the final line to identify their group, such as:

Line1:          The 
Line2:   Eagle's Nest
Line3:
Line4:      (Castle)

I can only think of using RegEx across all the lines or possibly identifying what line to look for group information in.

Is such a feature worth adding?

**Comment by m0r13** [comment] 2016-06-28 15:47
Possible would be a regular expression and using the found groups for formatting the marker title/text, though this would be a feature for more advanced users.

In your use-case a postfix instead of a prefix would work too if I'm not wrong?

**Comment by agattis** [comment] 2016-06-28 15:49
Yes, post fix is the use case I've got.

**Comment by m0r13** [comment] 2016-06-30 13:00
I implemented the postfix option and did a quick test with it. Can you test if it works for you too? The change is in the master branch available.

**Comment by agattis** [comment] 2016-06-30 13:00
Will try now

**Comment by m0r13** [comment] 2016-07-01 18:07
I forgot to handle a special case. Maybe it works now?

**Comment by agattis** [comment] 2016-07-01 18:32
Seems to finish the run OK - I'll get you some detailed results in a few

**Comment by agattis** [comment] 2016-07-01 19:09
Nope, as soon as I added a Marker section it threw an exception

[marker:homes]
name = Homes
postfix = (House)


[allen@ip-10-194-1-145 mapcrafter]$ /srv/mapcrafter/src/mapcrafter_markers
-v -c /srv/mapcrafter/mapcrafter.conf

2016-07-01 19:07:27 [INFO] [progress] Loading entities of world
'Hinterlands' ...
2016-07-01 19:07:27 [INFO] [progress] 50% complete. Processed 1/2 items
with average inf/s.
2016-07-01 19:07:27 [INFO] [progress] 100% complete. Processed 2/2 items
with average inf/s.
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted

**Comment by agattis** [comment] 2016-07-01 19:12
I made the map and conf file available at

http://minecraft.gattis.org/maps/mapcrafter.conf
<http://minecraft.gattis.org/map/mapcrafter.conf>
http://minecraft.gattis.org/maps/Hinterlands.tgz

**Comment by m0r13** [comment] 2016-07-01 19:46
I'm not quite sure what the problem is, so I added a debug message. What's the output with that?

**Comment by agattis** [comment] 2016-07-01 20:09
Fails to compile now
 make
[  1%] Built target version.cpp
[  2%] Building CXX object
mapcraftercore/CMakeFiles/mapcraftercore.dir/config/configparser.o
In file included from /usr/include/c++/4.8.3/condition_variable:35:0,
                 from
/srv/mapcrafter/src/mapcraftercore/config/../util/../compat/thread.h:29,
                 from
/srv/mapcrafter/src/mapcraftercore/config/../util/logging.h:23,
                 from
/srv/mapcrafter/src/mapcraftercore/config/../util.h:36,
                 from
/srv/mapcrafter/src/mapcraftercore/config/iniconfig.h:23,
                 from
/srv/mapcrafter/src/mapcraftercore/config/configparser.h:23,
                 from
/srv/mapcrafter/src/mapcraftercore/config/configparser.cpp:20:
/usr/include/c++/4.8.3/bits/c++0x_warning.h:32:2: error: #error This file
requires compiler and library support for the ISO C++ 2011 standard. This
support is currently experimental, and must be enabled with the -std=c++11
or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from
/srv/mapcrafter/src/mapcraftercore/config/../util.h:36:0,
                 from
/srv/mapcrafter/src/mapcraftercore/config/iniconfig.h:23,
                 from
/srv/mapcrafter/src/mapcraftercore/config/configparser.h:23,
                 from
/srv/mapcrafter/src/mapcraftercore/config/configparser.cpp:20:



The full output is at http://minecraft.gattis.org/maps/error.log

**Comment by m0r13** [comment] 2016-07-01 20:31
Are you sure you are running make in the `mapcrafter/`-source directory, and not in `mapcrafter/src/` ?

**Comment by agattis** [comment] 2016-07-01 20:55
Indeed - I had not, thanks. After a successful compile, here's the output

[allen@ip-10-194-1-145 mapcrafter]$ /srv/mapcrafter/src/mapcrafter_markers
-v -c /srv/mapcrafter/mapcrafter.conf
2016-07-01 20:53:56 [INFO] [progress] Loading entities of world
'Hinterlands' ...
2016-07-01 20:53:56 [INFO] [progress] 50% complete. Processed 1/2 items
with average inf/s.
2016-07-01 20:53:56 [INFO] [progress] 100% complete. Processed 2/2 items
with average inf/s.
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted

**Comment by m0r13** [comment] 2016-07-01 21:09
Okay I'll try to debug that on my own. Unfortunately I can't reach your server with the config and the world you are using.

**Comment by agattis** [comment] 2016-07-01 21:10
Oh, my bad. Forgot about the security rules. Will open it up later tonight

**Comment by m0r13** [comment] 2016-07-02 12:00
Now it should really work. :)
I was able to fix it with your map.

**Comment by agattis** [comment] 2016-07-04 19:11
Success! I'll run a larger section of markers to confirm, but we look good

**Comment by m0r13** [comment] 2016-07-04 19:13
That's good. I'm building packages for a new version right now.

**Comment by agattis** [comment] 2016-07-04 20:08
Seems to generate the markers OK, but after running a map render, I now get
only blank pages from the web server (same config file as with previous
versions). There are files in the HTML directory but something is up. I'll
troubleshoot some later tonight and give you an update.

**Comment by m0r13** [comment] 2016-07-04 20:29
Yup I did a small mistake there. Problem should be fixed in the next nightly or current stable package.

**Comment by agattis** [comment] 2016-07-05 15:28
That seems to have fixed the map issue and resolves the postfix feature
request. I ran some larger sections, and features such as %(textp)
title_format work as well.

Many Thanks!

**Closed** 2016-07-05 16:05 UTC
Labels: Feature Request
